baseURL = 'https://dfghj.de'
languageCode = 'en-us'
title = "Alex' Blog"
theme = 'archie'

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
pagerSize = 5

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/alex-ruehe"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "CV"
url = "https://aruehe.io"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[params]
    mode = "toggle"
    useCDN=false
    customcss = ["css/carousel.css"]